"""add celery_task_id to pipeline_runs

Revision ID: 201bedf4e8a5
Revises: 92933928b7a8
Create Date: 2026-04-18 17:15:07.314703
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201bedf4e8a5'
down_revision: Union[str, None] = '92933928b7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('celery_task_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'celery_task_id')
    # ### end Alembic commands ###
