"""add cdc_jobs and cdc_sync_logs tables

Revision ID: 92933928b7a8
Revises: d06c7f9c2105
Create Date: 2026-03-14 14:25:32.476441
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92933928b7a8'
down_revision: Union[str, None] = 'd06c7f9c2105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdc_jobs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'PAUSED', 'FAILED', name='cdcstatus'), nullable=False),
    sa.Column('source_schema', sa.String(length=255), nullable=False),
    sa.Column('source_table', sa.String(length=255), nullable=False),
    sa.Column('tracking_column', sa.String(length=255), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_prefix', sa.String(length=500), nullable=False),
    sa.Column('s3_region', sa.String(length=50), nullable=False),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_value', sa.Text(), nullable=True),
    sa.Column('total_rows_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdc_sync_logs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_captured', sa.Integer(), nullable=False),
    sa.Column('s3_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['cdc_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cdc_sync_logs')
    op.drop_table('cdc_jobs')
    # ### end Alembic commands ###
